package river:types@0.1.0;

interface filter-factory {
    type config = list<tuple<string, string>>;

    resource filter-instance {
        on-request: func() -> result<_, string>;
        on-response: func() -> result<_, string>;
    }

    create: func(name: string, config: config) -> result<filter-instance, string>;
}
